version: "3.4"

services:
  app:
    build: app
    image: app
    restart: "no"
    volumes:
      - ./shopping-lists/:/app
      - ./app-cache/:/app-cache
    ports:
      - 7777:7777

  e2e-playwright:
    entrypoint: "/bin/true" # Prevent startup on docker-compose up
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - app
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests
